FROM node:20

COPY ./server/package.json /node-app/

RUN cd /node-app && npm install --production

WORKDIR /node-app

COPY ./server/libs ./libs
COPY ./server/messageTemplate ./messageTemplate
COPY ./server/* ./

COPY ./build ./build

EXPOSE 8040

# 启动应用
CMD ["npm", "run", "start"]

